class DoctorCategories {
  static const List<String> categories = [
    'Addiction Medicine Specialist',
    'Allergist/Immunologist',
    'Anesthesiologist',
    'Cardiologist',
    'Chiropractor',
    'Clinical Pharmacologist',
    'Clinical Psychologist',
    'Critical Care Specialist',
    'Dentist',
    'Dermatologist',
    'Emergency Medicine Specialist',
    'Endocrinologist',
    'ENT Specialist (Otolaryngologist)',
    'Family Medicine Physician',
    'Forensic Pathologist',
    'Gastroenterologist',
    'General Physician',
    'Geriatrician',
    'Gynecologist',
    'Hematologist',
    'Holistic Medicine Practitioner',
    'Hospitalist',
    'Hyperbaric Medicine Specialist',
    'Infectious Disease Specialist',
    'Integrative Medicine Specialist',
    'Maxillofacial Surgeon',
    'Medical Geneticist',
    'Neonatologist',
    'Nephrologist',
    'Neurologist',
    'Occupational Medicine Specialist',
    'Oncologist',
    'Ophthalmologist',
    'Orthopedic',
    'Pain Management Specialist',
    'Pathologist',
    'Pediatric Surgeon',
    'Pediatrician',
    'Physiotherapist',
    'Plastic Surgeon',
    'Podiatrist',
    'Pulmonologist',
    'Psychiatrist',
    'Radiologist',
    'Reproductive Endocrinologist',
    'Rheumatologist',
    'Sleep Medicine Specialist',
    'Sports Medicine Specialist',
    'Thoracic Surgeon',
    'Trauma Surgeon',
    'Transplant Surgeon',
    'Urologist',
    'Vascular Surgeon',
    'Veterinary Doctor'
  ];
}
