import 'package:flutter/material.dart';

class PrivacyPolicyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(backgroundColor: Colors.white,
      appBar: AppBar(
        title: const Text('Privacy Policy'),
        backgroundColor: Colors.white
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: ListView(
          children: const [
            Text(
              'Privacy Policy',
              style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 10),
            Text(
              'Last updated: November 25, 2024',
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 20),
            Text(
              'This Privacy Policy describes Our policies and procedures on the collection, '
              'use and disclosure of Your information when You use the Service and tells You '
              'about Your privacy rights and how the law protects You.\n\n'
              'We use Your Personal data to provide and improve the Service. By using the '
              'Service, You agree to the collection and use of information in accordance with '
              'this Privacy Policy. This Privacy Policy has been created with the help of the '
              '[Free Privacy Policy Generator](https://www.freeprivacypolicy.com/free-privacy-policy-generator/).',
              style: TextStyle(fontSize: 14),
            ),
            SizedBox(height: 20),
            Text(
              'Interpretation and Definitions',
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 10),
            Text(
              'Interpretation\nThe words of which the initial letter is capitalized have meanings defined under the following conditions. '
              'The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.\n\n'
              'Definitions\nFor the purposes of this Privacy Policy:\n'
              '- Account means a unique account created for You to access our Service or parts of our Service.\n'
              '- Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" '
              'means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.\n'
              '- Application refers to Doctor Connect, the software program provided by the Company.\n'
              '- Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Doctor Connect.\n'
              '- Country refers to: Kerala, India.\n'
              '- Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.\n'
              '- Personal Data is any information that relates to an identified or identifiable individual.\n'
              '- Service refers to the Application.\n'
              '- Service Provider means any natural or legal person who processes the data on behalf of the Company.\n'
              '- Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.\n'
              '- You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
              style: TextStyle(fontSize: 14),
            ),
            SizedBox(height: 20),
            Text(
              'Collecting and Using Your Personal Data',
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 10),
            Text(
              'Types of Data Collected\nPersonal Data\nWhile using Our Service, We may ask You to provide Us with certain personally '
              'identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:\n'
              '- Email address\n- First name and last name\n- Phone number\n- Usage Data\n\n'
              'Usage Data\nUsage Data is collected automatically when using the Service. It may include information such as Your Device\'s Internet Protocol address, '
              'browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, and other diagnostic data.',
              style: TextStyle(fontSize: 14),
            ),
            SizedBox(height: 20),
            Text(
              'Contact Us',
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 10),
            Text(
              'If you have any questions about this Privacy Policy, You can contact us:\n'
              'By email: fouzanp.offical@gmail.com',
              style: TextStyle(fontSize: 14),
            ),
          ],
        ),
      ),
    );
  }
}
